# -*- coding: utf-8 -*-
"""7주차

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sGJdcY1Bk9qm9GnJjPlDdQOlsXlgwuP2
"""

import pandas as pd

df_t = pd.read_csv('/content/train.csv')
df_t

"""가격 별로 분류 분석"""

df_t[df_t['Fare']>=500]

df_t[df_t['Fare']==0]

항구별 좌석 등급 평균

df_t.groupby(['Embarked','Pclass'])['Fare'].mean()

df_t.groupby(['Embarked','Pclass'])['Fare'].max()

import matplotlib.pyplot as plt
import seaborn as sns

"""박스플롯 데이터"""

sns.boxplot(data=df_t,y='Fare', x='Embarked',hue='Pclass')
plt.show

비어있는 인덱스 채우거나 삭제하기

df_t.isna().sum()

df_sfill = df_t.fillna(100)
df_sfill

df_t['Age'].mean()

df_t['Age'] = df_t['Age'].fillna(df_t['Age'].mean())

df_t

df_t.isna().sum()

df_t.drop('Cabin',axis = 1 ,inplace = True)

df_t

df_t['Embarked'] = df_t['Embarked'].fillna('S')

df_t.isna().sum()

df_t.info()

"""박스플롯 그리기"""

sns.boxplot(data=df_t,x='Embarked',y='Fare')
plt.show()

"""여성 남성 생존율"""

df_t.groupby(['Sex','Survived']).count()

"""바 플롯 그리기"""

sns.barplot(data=df_t, x='Sex', y='Survived')
plt.show()

"""탑승좌석 등급별 생존"""

sns.barplot(data=df_t,x='Pclass',y='Survived')
plt.show()

"""탑승좌석 등급 + 성별"""

sns.barplot(data=df_t,x='Pclass',y='Survived',hue='Sex')
plt.show()

sns.barplot(x='Embarked',y='Survived',data = df_t)
plt.show()

"""히스토그램 그리기"""

sns.histplot(df_t['Age'],bins=30)
plt.show()

"""나이 구분 컬럼 apply"""

def AgeDiff(Age):
  if Age < 16:
    return '어린이'
  elif Age < 50:
    return '성인'
  else:
    return '노인'

df_t['AgeDiff'] = df_t['Age'].apply(AgeDiff)

df_t

df_t['Age'].max()

df_t.groupby(['Embarked'])['Fare'].mean()

sns.barplot(data=df_t,x='Embarked',y='Survived',hue='Sex')
plt.show()